#  version: "3.8" Docker Compose moderno ya la considera obsoleta.

services:
  # ─────────────────────────────────────────
  # MongoDB Community — Base de datos NoSQL
  # ─────────────────────────────────────────
  mongodb:
    image: mongo:7.0
    container_name: entel_mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: entel_bigdata
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # ─────────────────────────────────────────
  # Apache Airflow — Webserver (interfaz UI)
  # ─────────────────────────────────────────
  airflow-webserver:
    image: apache/airflow:2.8.0-python3.11
    container_name: entel_airflow_web
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__SECRET_KEY=entel2026secret
      # Variables propias del proyecto, inyectadas a los scripts via os.getenv()
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/
      - MONGO_DB_NAME=entel_bigdata
      - DATA_RAW_PATH=/opt/airflow/data/raw
      - DATA_PROCESSED_PATH=/opt/airflow/data/processed
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./airflow:/opt/airflow/config
      - ./requirements-airflow.txt:/requirements-airflow.txt
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "pip install --no-cache-dir -r /requirements-airflow.txt && airflow webserver"
    depends_on:
      - mongodb

  # ─────────────────────────────────────────
  # Apache Airflow — Scheduler (ejecuta los DAGs)
  # ─────────────────────────────────────────
  airflow-scheduler:
    image: apache/airflow:2.8.0-python3.11
    container_name: entel_airflow_scheduler
    restart: always
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - MONGO_URI=mongodb://admin:admin123@mongodb:27017/
      - MONGO_DB_NAME=entel_bigdata
      - DATA_RAW_PATH=/opt/airflow/data/raw
      - DATA_PROCESSED_PATH=/opt/airflow/data/processed
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data:/opt/airflow/data
      - ./airflow:/opt/airflow/config
      - ./requirements-airflow.txt:/requirements-airflow.txt
      - airflow_logs:/opt/airflow/logs
    command: >
      bash -c "pip install --no-cache-dir -r /requirements-airflow.txt && airflow scheduler"
    depends_on:
      - mongodb
      - airflow-webserver

volumes:
  mongo_data:
  airflow_logs:
